services:
  - type: web
    name: movie-bot
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y libssl-dev python3-dev build-essential gcc
      pip install -r requirements.txt
    startCommand: python bot.py
